spring:
  application:
    name: zuul

server:
  port: 8768

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

# 要禁用的过滤器 SendResponseFilter 处理正常的请求响应
uul:
  SendResponseFilter:
    post:
      disable: true
