# 使用 Feign 和 Hystrix 实现的服务消费者

server:
  port: 8765

spring:
  application:
    name: eureka-producer-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/


feign:
  hystrix:
    enabled: true