spring:
  application:
    name: produceMq
server:
  port: 9005

apache:
  rocketmq:
    consumer:
      PushConsumer: PushConsumer
    producer:
      producerGroup: Producer
    namesrvAddr: 127.0.0.1:9876
## eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    instance:
      prefer-ip-address: true