# 设置spring应用命名，可以自定义，非必要
spring:
  application:
    name: eureka-server
# 设置Eureka Server WEB控制台端口，自定义
server:
  port: 8762

#eureka 信息
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #是否将自己注册到Eureka-Server中，默认的为true
    fetchRegistry: false   #是否从Eureka-Server中获取服务注册信息，默认为true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #设置eureka服务器所在的地址，查询服务和注册服务程序都注册到这个地址(服务暴露的地址)
